### ISSUE TITLE
ReferenceError: _readFileSync is not defined

### ISSUE THREAD

**Issue by OttlikG** [ArnoSaine/babel-plugin-transform-import-to-read-file-sync#1]
It looks like fs lib is not in scope.
I think the problem is around this line:
https://github.com/ArnoSaine/babel-plugin-transform-import-to-read-file-sync/blob/master/src/index.js#L77

I get the following error in terminal.
```js
const Search = _readFileSync(require.resolve("./search.graphql"), "utf8");
               ^

ReferenceError: _readFileSync is not defined
```

I use the plugin alog with the latet babel config:
```js
"@babel/polyfill": "^7.0.0-beta.44",
"@babel/core": "^7.0.0-beta.44",
"@babel/node": "^7.0.0-beta.44",
"@babel/preset-env": "^7.0.0-beta.44",
```

**Comment by ArnoSaine** [comment]
Thank you for reporting the error.

I could't reproduce the error with those exact versions of the packages and a simple example. Can you perhaps provide a minimal `.babelrc` and sample source code to reproduce the error so I'm able to help?

**Comment by OttlikG** [comment]
If you run the appliction with the start script you should see the error:
https://github.com/OttlikG/graphql-layer

I couldn't reproduce with a simpler code base.

**Comment by ArnoSaine** [comment]
I got the error. It happens when using more than one `import file from 'file.zyx'` in a file and preset-env to transform modules to CommonJS. After the transformation code looks like this:

```js
var _fs = require("fs");
// ...
const AspectFilter = (0, _fs.readFileSync)(require.resolve("./common/aspect_filter.graphql"), "utf8");
const FilterField = _readFileSync(require.resolve("./common/filter_field.graphql"), "utf8");
const RangeValue = _readFileSync(require.resolve("./common/range_value.graphql"), "utf8");
```

Only the first `import` is transformed ok. This needs more investigation, because CommonJS transformation happens outside of this plugin.

Until a fix, workaround is to use require calls in the source file:

```js
const AspectFilter = require('./common/aspect_filter.graphql');
const FilterField = require('./common/filter_field.graphql');
const RangeValue = require('./common/range_value.graphql');
```

**Comment by OttlikG** [comment]
Thanks.
I got around using webpack with a loader.
